name: ci

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Theos Setup
        uses: Randomblock1/theos-action@v1

      - name: Setup libSandy
        run: |
          git clone https://github.com/realthunder/mac-headers --depth 1
          mv mac-headers/usr/include/xpc $THEOS/include
          git clone https://github.com/opa334/libSandy vendor/libSandy --depth 1
          cd vendor/libSandy/ && ./install_to_theos.sh && cd -

      - name: Setup AltList
        run: |
          git clone https://github.com/opa334/AltList --depth 1
          cd AltList && ./install_to_theos.sh && cd -

      - name: Build shadow
        run: ./build.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ github.workspace }}/packages/*.deb
          tag_name: rootless
          name: Rootless
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
